# Generated by Django 4.1.3 on 2022-11-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='balance',
            new_name='amount',
        ),
    ]
