# Generated by Django 4.1.3 on 2022-11-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_balance_paymentrequest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
