# Generated by Django 4.1.3 on 2022-11-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_paymentrequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_added',
            field=models.BooleanField(default=True),
        ),
    ]
