# Generated by Django 4.1.3 on 2022-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_is_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_added',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
